const timelineElements = [
    // {
    //     id: 1,
    //     title: "Graduated from University",
    //     location: "Cavite State University Silang Campus",
    //     description: "Completed my degree in Computer Science",
    //     buttonText: "Details",
    //     date: "2014-2018",
    //     icon: "school",
    //     color: "white",
    //     tech: ["JavaScript", "HTML", "CSS", "Java"],
    // },
    {
        id: 2,
        title: "Currently Pursuing Bachelor's in Computer Science",
        location: "Cavite State University",
        description: "Engaged in coursework and projects, seeking internships to enhance skills.",
        buttonText: "To be Continued",
        date: "2018-present",
        icon: "school",
        color: "orange",
        tech: ["ReactJS", "HTML", "CSS", "JavaScript", "Material-UI", "Chakra-UI", "Shadcn UI", "Node.js", "Express.js", "Mongoose", "MongoDB", "MySQL", "REST API", "Electron.js", "Angular",],
    },
    {
        id: 3,
        title: "Water Refilling Management System",
        location: "Cavite State University",
        description: "Developed a comprehensive system for managing water refilling operations, including client, employee, and admin interfaces.",
        buttonText: "Details",
        date: "2019-2021",
        icon: "work",
        color: "yellow",
        tech: ["MongoDB", "Express.js", "ReactJS", "Node.js", "JavaScript", "TypeScript", "Material UI", "Shadcn UI", "Mongoose", "REST API"],
    },
    {
        id: 4,
        title: "Hotel Booking Website",
        location: "Cavite State University",
        description: "Designed and implemented a hotel booking website as part of the Software Engineering and Advanced Database Management System projects.",
        buttonText: "Details",
        date: "2021-2023",
        icon: "work",
        color: "red",
        tech: ["Node.js", "ReactJS", "SQL", "JavaScript", "CSS", "REST API"],
    },
    {
        id: 5,
        title: "Cavite State University",
        location: "J. Rizal, Silang, Cavite",
        description: "Enrolled in a Bachelor of Science program in Computer Science, gaining knowledge in various programming languages and concepts.",
        buttonText: "Details",
        date: "2021-present",
        icon: "school",
        color: "orange",
        tech: ["HTML", "CSS", "C++", "Java", "Object-Oriented Programming", "JavaScript"],
    },
];

export default timelineElements.reverse();
